const escapeHtml = (value) => {
    return String(value || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
};

const getMonthDay = (timeZone) => {
    const parts = new Intl.DateTimeFormat('en-US', {
        timeZone: timeZone || 'UTC',
        month: 'numeric',
        day: 'numeric',
    }).formatToParts(new Date());

    const monthPart = parts.find((part) => part.type === 'month');
    const dayPart = parts.find((part) => part.type === 'day');

    return {
        month: Number(monthPart?.value || 0),
        day: Number(dayPart?.value || 0),
    };
};

const formatDateLabel = (dateValue, timeZone) => {
    if (!dateValue) return '';
    const date = new Date(dateValue);
    if (Number.isNaN(date.getTime())) return '';

    return new Intl.DateTimeFormat('en-US', {
        timeZone: timeZone || 'UTC',
        year: 'numeric',
        month: 'short',
        day: 'numeric',
    }).format(date);
};

const buildRecordDrafts = (records, timeZone) => {
    return records.map((record) => {
        const categoryName = (record.category?.name || 'Record').trim();
        const categoryKey = categoryName.toLowerCase();
        const isBirthday = categoryKey.includes('bday') || categoryKey.includes('birthday');
        const isAnnouncement = categoryKey.includes('announcement') || categoryKey.includes('event');
        const isDocument = categoryKey.includes('doc') || categoryKey.includes('document');

        let title = `Record: ${record.title}`;
        let message = `Update: ${record.description || record.title}`;

        if (isBirthday) {
            title = `Birthday: ${record.title}`;
            message = `Happy Birthday, ${record.title}! Wishing you all the best today!`;
            if (record.description) {
                message += `\n${record.description}`;
            }
        } else if (isAnnouncement) {
            title = `Announcement: ${record.title}`;
            message = `Announcement: ${record.description || record.title}`;
        } else if (isDocument) {
            title = `Document: ${record.title}`;
            message = `Document: ${record.title}`;
            if (record.description) {
                message += `\nDetails: ${record.description}`;
            }
        }

        const dateLabel = formatDateLabel(record.date, timeZone)
            || (record.date ? new Date(record.date).toISOString().split('T')[0] : '');

        return {
            id: String(record._id || ''),
            typeLabel: categoryName || 'record',
            title,
            message,
            dateLabel,
        };
    });
};

const renderDraftEmail = (drafts, options = {}) => {
    const title = options.title || 'Post Drafts Ready';
    const dateLabel = options.dateLabel ? `Date: ${options.dateLabel}` : '';

    const cards = drafts
        .map((draft) => {
            return `
            <div style="border:1px solid #e5e7eb; border-radius:12px; padding:16px; margin-bottom:12px;">
                <div style="font-size:14px; font-weight:600; color:#111827;">${escapeHtml(draft.title)}</div>
                <div style="font-size:12px; color:#6b7280; margin-top:4px;">Type: ${escapeHtml(draft.typeLabel)} | Date: ${escapeHtml(draft.dateLabel)}</div>
                <div style="margin-top:12px; padding:12px; background:#f3f4f6; border-radius:8px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; font-size:13px; white-space:pre-wrap;">${escapeHtml(draft.message)}</div>
            </div>
        `;
        })
        .join('');

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
</head>
<body style="margin:0; padding:24px; background:#f9fafb; font-family: Arial, sans-serif; color:#111827;">
  <div style="max-width:720px; margin:0 auto; background:#ffffff; border:1px solid #e5e7eb; border-radius:16px; padding:24px;">
    <h2 style="margin:0 0 8px; font-size:20px;">${escapeHtml(title)}</h2>
    <p style="margin:0 0 16px; color:#6b7280; font-size:13px;">${escapeHtml(dateLabel)}</p>
    ${cards}
    <p style="margin:16px 0 0; font-size:12px; color:#6b7280;">Generated by RecordMS</p>
  </div>
</body>
</html>`;
};

const renderDraftText = (drafts, options = {}) => {
    const header = options.title || 'Post Drafts Ready';
    const dateLabel = options.dateLabel ? `Date: ${options.dateLabel}` : '';

    const body = drafts
        .map((draft, index) => {
            return [
                `${index + 1}. ${draft.title}`,
                `Type: ${draft.typeLabel}`,
                `Date: ${draft.dateLabel}`,
                'Post Copy:',
                draft.message,
            ].join('\n');
        })
        .join('\n\n---\n\n');

    return [header, dateLabel, '', body].filter(Boolean).join('\n');
};

module.exports = {
    getMonthDay,
    formatDateLabel,
    buildRecordDrafts,
    renderDraftEmail,
    renderDraftText,
};
